site_name: Entity Extraction & Knowledge API
site_description: Comprehensive entity extraction and knowledge API with Wikipedia linking
site_author: Entity Extraction Team
site_url: https://janschachtschabel.github.io/entity-extractor-linker-api/

repo_name: janschachtschabel/entity-extractor-linker-api
repo_url: https://github.com/janschachtschabel/entity-extractor-linker-api

theme:
  name: mkdocs
  nav_style: dark

nav:
  - Home: index.md
  - API Reference:
    - Overview: api/overview.md
    - Endpoints: api/endpoints.md
  - Architecture:
    - Overview: architecture/overview.md
  - Development:
    - Setup: development/setup.md

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
